export enum PaymentConcepts {
  NEW_MEMBERSHIP = 'SOCIO NUEVO',
  RENEW_MEMBERSHIP = 'RENOVACION',
  PRE_PAY_MEMBERSHIP = 'RENOVACION-ADELANTO-',
  FREE_MEMBERSHIP = 'RENOVACION-MES-GRATIS',
  PRE_PAY_FREE_MEMBERSHIP = 'RENOVACION-MES-GRATIS-ADELANTO-'
}